
export const OUTPASS_LIST_REQUEST = "OUTPASS_LIST_REQUEST";
export const OUTPASS_LIST_SUCCESS = "OUTPASS_LIST_SUCCESS";
export const OUTPASS_LIST_FAIL = "OUTPASS_LIST_FAIL";

export const OUTPASS_CREATE_REQUEST = "OUTPASS_CREATE_REQUEST";
export const OUTPASS_CREATE_SUCCESS = "OUTPASS_CREATE_SUCCESS";
export const OUTPASS_CREATE_FAIL = "OUTPASS_CREATE_FAIL";

