
export const REGISTER_LIST_REQUEST = "REGISTER_LIST_REQUEST";
export const REGISTER_LIST_SUCCESS = "REGISTER_LIST_SUCCESS";
export const REGISTER_LIST_FAIL = "REGISTER_LIST_FAIL";

export const REGISTER_CREATE_REQUEST = "REGISTER_CREATE_REQUEST";
export const REGISTER_CREATE_SUCCESS = "REGISTER_CREATE_SUCCESS";
export const REGISTER_CREATE_FAIL = "REGISTER_CREATE_FAIL";

